### ISSUE TITLE
bisschen blöd soviele Abhängigkeiten jetzt braucht man bash python und ruby...

### ISSUE THREAD

**Issue by netinetwalker** [ZoeShi/Mumble-Plugin-Bot-Gui#2]
bisschen blöd soviele Abhängigkeiten jetzt braucht man bash python und ruby...

**Comment by ZoeShi** [comment]
Die Abhängigkeiten bringt der Bot auch so schon mit ("youtube-dl" braucht Python, der Bot braucht Bash für das Startscript und Ruby sowieso).

Das einzige was dazu kommt ist pygtk, aber für eine GUI braucht man eben ein UI Toolkit.

Deshalb ist das kein wirklicher Bug.

**Comment by netinetwalker** [comment]
@ZoeShi you have successfully unlocked a real life award: "Counter-Troll - troll a troll" - Award

**Comment by dafoxia** [comment]
Der Bot hat diese Abhängigkeiten nicht! Das sind (standardmässig aktivierte) Plugins!
Wer diese Plugins nicht braucht hat auch diese Abhängigkeiten nicht!
